/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.igor.todolist;

import com.igor.todolist.controller.TaskController;
import com.igor.todolist.dao.TasksDAO;
import com.igor.todolist.model.Task;
import com.igor.todolist.view.TaskView;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {

        boolean end = true;
        ArrayList<Task> tasks = new ArrayList<>();
        Scanner sc = new Scanner(System.in);
        TasksDAO.readTasks(tasks);

        menu();

        while (end) {
            System.out.println("Escolha uma opção do menu:");
            int opc = sc.nextInt();
            switch (opc) {
                case 1 ->
                    // Criando uma tarefa
                        tasks.add(TaskController.criarTarefa());
                case 2 ->
                    // Listar tarefas por prioridade
                        TaskView.listarTarefas(tasks, Comparator.comparing(Task::getNivel_prioridade));
                case 3 ->
                    // Listar tarefas por categoria
                        TaskView.listarTarefas(tasks, Comparator.comparing(Task::getCategoria));
                case 4 ->
                    // Listar tarefa por status
                        TaskView.listarTarefas(tasks, Comparator.comparing(Task::getStatus));
                case 5 ->
                    // Listar tarefa por data de termino
                        TaskView.listarTarefas(tasks, Comparator.comparing(Task::getData_termino));
                case 6 ->
                    // Verificar número de tarefas concluidas, estão para fazer e sendo feitas
                        System.out.println(TaskView.contaTarefas(tasks));
                case 7 ->
                    // Modificar uma tarefa
                        TaskController.atualizarTarefa(tasks);
                case 8 ->
                    // Remover uma tarefa
                        TaskController.excluirTarefa(tasks);
                case 9 -> {
                    // Sair do programa
                    System.out.println("Programa finalizado!");
                    TasksDAO.writeTasks(tasks);
                    end = false;
                }
                default -> System.out.println("Comando incorreto!");
            }
        }
        sc.close();
    }
    public static void menu() {
        System.out.println("1 - Adicionar uma nova tarefa");
        System.out.println("2 - Listar tarefa por prioridade");
        System.out.println("3 - Listar tarefa por categoria");
        System.out.println("4 - Listar tarefa por status");
        System.out.println("5 - Listar tarefa por data de termino");
        System.out.println("6 - Verificar número de tarefas concluidas, estão para fazer e sendo feitas");
        System.out.println("7 - Modificiar uma tarefa");
        System.out.println("8 - Remover uma tarefa");
        System.out.println("9 - Sair");
    }
}
